Update licensee to at least 9.7.0
Older versions of licensee don't work with newer versions of rugged, so
ensure we have at least this version to avoid the error:

```
extconf.rb:101:in `block in <main>': undefined method `exists?' for class Dir
(NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
	from extconf.rb:100:in `chdir'
	from extconf.rb:100:in `<main>'

...

An error occurred while installing rugged (0.99.0), and Bundler cannot continue.

In Gemfile:
  multi_repo was resolved to 1.0.0, which depends on
    licensee was resolved to 9.6.0, which depends on
      rugged
```